apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patroni-data
  namespace: business-ha-production
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: business-ha-zfs-retain-16k
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patroni-pre-rewind
  namespace: business-ha-production
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: business-ha-zfs-retain-16k
  resources:
    requests:
      storage: 16Gi
