apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: business-ha-zfs-retain-16k
provisioner: zfs.csi.openebs.io
parameters:
  atime: "off"
  compression: lz4
  dedup: "off"
  fstype: zfs
  logbias: latency
  poolname: speed
  recordsize: 16k
  shared: "yes"
  thinprovision: "yes"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
