---
apiVersion: "cilium.io/v2"
kind: "CiliumNetworkPolicy"
metadata:
  name: "dealer-agent-jobs"
spec:
  endpointSelector:
    matchLabels:
      dealer.agent/installation: "mk-development"
      dealer.agent/role: "jobs"
  ingress:
    - fromEndpoints:
        - matchLabels:
            dealer.agent/installation: "mk-development"
            dealer.agent/role: "controller"
      toPorts:
        - ports:
            - port: "8644"
              protocol: "TCP"
  egress:
    - toEndpoints:
        - matchLabels:
            dealer.agent/installation: "mk-development"
            dealer.agent/role: "controller"
      toPorts:
        - ports:
            - port: "8788"
              protocol: "TCP"
  egressDeny:
    - toEntities:
        - "world"
        - "host"
        - "remote-node"
        - "kube-apiserver"
