---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "dealer-agent-controller"
automountServiceAccountToken: false
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "dealer-agent-worker"
automountServiceAccountToken: false
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "dealer-agent-controller"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/proxy"
    verbs:
      - "get"
      - "create"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
      - "delete"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "create"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    resourceNames:
      - "dealer-agent-worker-0beb3098ec79"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "services"
    resourceNames:
      - "dealer-agent"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "resourcequotas"
    resourceNames:
      - "dealer-agent"
    verbs:
      - "get"
  - apiGroups:
      - "cilium.io"
    resources:
      - "ciliumnetworkpolicies"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "networkpolicies"
    verbs:
      - "list"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    resourceNames:
      - "dealer-agent-controller"
    verbs:
      - "get"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "dealer-agent-controller"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "dealer-agent-controller"
subjects:
  - kind: "ServiceAccount"
    name: "dealer-agent-controller"
    namespace: "dealer-mk-development"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "dealer-mk-development-namespace-read"
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    resourceNames:
      - "dealer-mk-development"
    verbs:
      - "get"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "dealer-mk-development-namespace-read"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "dealer-mk-development-namespace-read"
subjects:
  - kind: "ServiceAccount"
    name: "dealer-agent-controller"
    namespace: "dealer-mk-development"
