---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "dealer-mk-development"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
  labels:
    dealer.agent/installation: "mk-development"
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "v1.35"
