[env]
_.file = '{{config_root}}/.talos.env'
KUBECONFIG = '{{config_root}}/kubeconfig'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'
TALOSCONFIG = '{{config_root}}/talosconfig'
PATH = '{{config_root}}/.tasks'
