---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game
components:
  - ../../components/common
  - ../../components/kopiur/secret
resources:
  - ./minecraft/ks.yaml
  - ./minecraft-rotational/ks.yaml
  - ./valheim/ks.yaml
  - ./palworld/ks.yaml
  - ./addon-filebrowser/ks.yaml
