---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bighorn-byte-browser-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bighorn-byte-browser-secret
    template:
      data:
        browser.json: |
          {
            "host": "0.0.0.0",
            "port": 3000,
            "wsPath": {{ .BROWSER_WS_PATH | toJson }},
            "headless": true,
            "chromiumSandbox": true
          }
  dataFrom:
    - extract:
        key: bighorn-byte-outreach
