cluster:
  id: 2
  name: upcloud-trial
ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: false
routingMode: tunnel
tunnelProtocol: vxlan
kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
bpf:
  hostLegacyRouting: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
operator:
  replicas: 1
envoy:
  enabled: false
hubble:
  enabled: false
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
