---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp130s0f0np0
rings:
  rx: 8192
  tx: 8192
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp130s0f1np1
rings:
  rx: 8192
  tx: 8192
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.serial == "PHM2911201VL960CGN"
  maxSize: 100GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: disk.serial == "PHM2911201VL960CGN"
  minSize: 500GiB
  grow: true
