---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bighorn-byte-development-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bighorn-byte-development-secret
  data:
    - secretKey: PGUSER
      remoteRef:
        key: bighorn-byte-development
        property: PGUSER
    - secretKey: PGPASSWORD
      remoteRef:
        key: bighorn-byte-development
        property: PGPASSWORD
    - secretKey: ADMIN_PGUSER
      remoteRef:
        key: bighorn-byte-development
        property: ADMIN_PGUSER
    - secretKey: ADMIN_PGPASSWORD
      remoteRef:
        key: bighorn-byte-development
        property: ADMIN_PGPASSWORD
    - secretKey: ADMIN_ENCRYPTION_KEYS
      remoteRef:
        key: bighorn-byte-development
        property: ADMIN_ENCRYPTION_KEYS
    - secretKey: ADMIN_ENCRYPTION_KEY_ID
      remoteRef:
        key: bighorn-byte-development
        property: ADMIN_ENCRYPTION_KEY_ID
    - secretKey: ADMIN_LOOKUP_KEY
      remoteRef:
        key: bighorn-byte-development
        property: ADMIN_LOOKUP_KEY
