---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcxboxbroadcast-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfs-64k
