---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: connelybrothers-origin
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: connelybrothers-origin
  apiKeyAuth:
    credentialRefs:
      - name: connelybrothers-origin-secret
    extractFrom:
      - headers: [X-HA-Origin-Token]
    sanitize: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: connelybrothers-monitor
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: connelybrothers-monitor
  apiKeyAuth:
    credentialRefs:
      - name: connelybrothers-monitor-secret
    extractFrom:
      - headers: [Authorization]
    sanitize: true
