---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-rec-1
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-rec-1-secret
    template:
      data:
        NEXTCLOUD_USERNAME: "{{ .USER }}"
        NEXTCLOUD_PASSWORD: "{{ .PASS }}"
  dataFrom:
    - extract:
        key: nextcloud-rec-1
