---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: upcloud-ha-prod-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  local:
    path: /var/mnt/ha-prod-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - trial-talos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patroni
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ''
  volumeName: upcloud-ha-prod-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: upcloud-ha-prod-forensic
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  local:
    path: /var/mnt/ha-prod-forensic
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - trial-talos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patroni-forensic
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ''
  volumeName: upcloud-ha-prod-forensic
  resources:
    requests:
      storage: 16Gi
