---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: business-ghcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: business-ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .DOCKER_CONFIG }}"
  dataFrom:
    - extract:
        key: business-ghcr
