---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silence-operator
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/observability/silence-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silence-operator-silences
  namespace: &namespace observability
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: silence-operator
  interval: 1h
  path: ./kubernetes/apps/observability/silence-operator/silences
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
