---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fcc-spam-reporter-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fcc-spam-reporter-secret
    template:
      data:
        QUO_API_KEY: "{{ .QUO_API_KEY }}"
        QUO_COMMAND_SENDERS: "{{ .QUO_COMMAND_SENDERS }}"
  dataFrom:
    - extract:
        key: fcc-spam-reporter
