---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: nvidia-device-plugin

  values:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: extensions.talos.dev/nvidia-open-gpu-kernel-modules-production
                    operator: Exists
    config:
      map:
        default: |-
          version: v1
          sharing:
            timeSlicing:
              renameByDefault: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
