apiVersion: v1
kind: Secret
metadata:
  name: cb-ha-domains
  namespace: flux-system
stringData:
  CB_TEST_HOME_FQDN: ENC[AES256_GCM,data:gce7leeQA5867fFwhlAUXJIwPtfVI1k8JUg6/UtvvJL0tT3F,iv:Q8O1tPZuYtTwLTpcdyNyn/pzs5P6g57Zv8r5RlZqWpU=,tag:WeYm50SCp9iGF8k+ImKfMw==,type:str]
  CB_TEST_CLOUD_FQDN: ENC[AES256_GCM,data:gv01NQXlU0IKpNQ46SfuwR1VPKxd1E8OG6itZFZvfYfNdWvDdA==,iv:M8PW5NPCJD4I10yLXwWN+OYiDgcUiC7jVsnVT3IYbyY=,tag:GK8J2Fau3temNF6uobNImw==,type:str]
  CB_PROD_HOME_FQDN: ENC[AES256_GCM,data:gdrbEC0tLhFtTuxvJUxzKUybWzt9Zgu5+Cu0VI3aHw==,iv:bAelPpo9X/Yiw4rOQY4C98AFa5FQJYN1+A2ke2Fz/g0=,tag:uysD4cdO0lHkS7a+33TmqQ==,type:str]
  CB_PROD_CLOUD_FQDN: ENC[AES256_GCM,data:XGlZ6t9ZX9vSsynt1RAoQtFXlwy6tJip8JNh8twDlGg=,iv:FVhIIavBOlZx3Chyfs/4uSwDDVbGuMEJ7VDKzmefRGc=,tag:53a0aUl1JZiQMAwcB/lDbg==,type:str]
  CB_PUBLIC_HOST: ENC[AES256_GCM,data:0/y0Q5EYEbyqI69V0iheqZ8K+w==,iv:P+o2+DQererqaW2GIxhJoaBeN0rTUx1uDqJwyvKc7Sg=,tag:IC3htAb8+2GM9jOoKvPf6Q==,type:str]
  CB_APEX_HOST: ENC[AES256_GCM,data:Gq4gVNaGah881OloPTFZ,iv:S08CX7LBXYequ4Nuw2ATf8eHY/YxKVBNWQgF7ZYeM6o=,tag:rK6tkE2r58KSalTX3YBYRg==,type:str]
  CB_IMAGES_HOST: ENC[AES256_GCM,data:VFI9Fkwmzp/Y2aKY+ZZ3sOWIWSxb,iv:ZftawJyAm4rOBBdJ37mV4Il8Mraiwm7r+AMC4Do2+6s=,tag:/VpM+KlS6pTiEwgNug4hhA==,type:str]
  CB_TEST_BACKUP_STANZA: ENC[AES256_GCM,data:s5StSLX6DhzPCccJ/sdB/H3Jg7Qn,iv:P1B3XUpOmOt2yE1Y5icmunXxIC2Tt9UCNEWAtJRT//M=,tag:7RfRg4N0X6+uaTOs0Sp3ew==,type:str]
  CB_PROD_BACKUP_STANZA: ENC[AES256_GCM,data:1WGYaT375ImC79kOQ5jsBpdrLHYE,iv:mwrCGMmWVU78BhgCUHHGtHB1AWQ5u9/nU6CdZ/6o+mE=,tag:qV4J4C4NhW9ObpktfRNtfQ==,type:str]
  CB_BUSINESS_NAME: ENC[AES256_GCM,data:qcRBWkgxsNsUNPUAMlwFqAMYAJi8Zk2qig==,iv:CD/UZDhP0K2VYaqchkaFqJtndpvyh00KMlng7bTh6J4=,tag:ou8a3K2EBdq8gD0O14X3OQ==,type:str]
  CB_BUSINESS_PHONE: ENC[AES256_GCM,data:EFxEmXmtODRP5/Y3,iv:IaLJ16xVHUC+l2BbP2R7jsxIHIJB2pIa4D9tZx3U/nE=,tag:DPddknftUqvBl3LFu0V8sw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOTdUVGo5T2Z3b2dnb0wx
        YkgzdmJDazdNcTRtMlloKzNqRzQ4clkvckNjCitrUFMycWdKMHFGdEIzcXI4akE1
        MitxcUcxTWpFLzZZanlHSG9Xa1dLOFkKLS0tIG92anYwcEN3Vk54QmNsK0orNHZM
        Q1FVanJJSE5kS25vR3ZUOU9NenVHdEEKgLlY+ojovHN525evyiGZ7YMMmmQFqIdE
        p1yz+5QELSfKGTVuKLb9zpkkj9yOurCE85ee/v4/RuHF5k4aNsE8Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age172ga8ydq62pezn7jcg2xkc4ytc4uf7ymzahvydqjszul30j2accstykn84
  encrypted_regex: ^stringData$
  lastmodified: "2026-10-03T04:00:48Z"
  mac: ENC[AES256_GCM,data:JPD2NIMMeyqx9MmhcFGuPiSOBiM+WOjC8bcg8ee/unrMiUUhfTZjU6QmIaZ4xZCmOgMBS3WvZaitkgROO70nR89yMOrfLRKTgcz4hkqx2RtZgm5vtrjiPUVEN/Nvcnw70lzVB+wdvjHSl+Uc9iOe3qPILmDOq7kxAtb4tQMAZsk=,iv:DghQ49ZgENg9wp7YsI/0xuren6T4WSWYom+tMJuQZ20=,tag:v160rLW1px1sK2IsR2Ssyg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
