---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: business
components:
  - ../../components/common
  - ../../components/kopiur/secret
resources:
  - ./agent-runner/registry-secret.yaml
  - ./bighorn-byte/ks.yaml
  - ./scale-tv/ks.yaml
  - ./docmost-bhb/ks.yaml
  - ./documenso/ks.yaml
  - ./agent-runner/ks.yaml
  - ./connelybrothers/ks.yaml
