---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-archiver-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mail-archiver-secret
    creationPolicy: Owner
    template:
      data:
        # Database Connection
        ConnectionStrings__DefaultConnection: "Host=postgres16-rw.database.svc.cluster.local;Database=mailarchiver;Username={{ .MAIL_ARCHIVER_POSTGRES_USER }};Password={{ .MAIL_ARCHIVER_POSTGRES_PASS }};"

        # Admin Authentication
        Authentication__Username: "{{ .MAIL_ARCHIVER_ADMIN_USER }}"
        Authentication__Password: "{{ .MAIL_ARCHIVER_ADMIN_PASS }}"

        # Init Container Variables
        INIT_POSTGRES_DBNAME: mailarchiver
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .MAIL_ARCHIVER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MAIL_ARCHIVER_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"

    - extract:
        key: mail-archiver
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MAIL_ARCHIVER_$1"
