apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: ha-runtime-scripts
  files:
  - scripts/pg_rewind
  - scripts/backup_scheduler.py
  - scripts/wal_metrics.py
generatorOptions:
  disableNameSuffixHash: true
