---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: kopiur
      namespace: kopiur-system

  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/readarr
              tag: 0.4.18.2805@sha256:8f7551205fbdccd526db23a38a6fba18b0f40726e63bb89be0fb2333ff4ee4cd
            env:
              READARR__APP__INSTANCENAME: Readarr
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__SERVER__PORT: &port 80
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: readarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              limits:
                cpu: 2
                memory: 5Gi
              requests:
                cpu: 10m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "readarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        existingClaim: *app

      tmp:
        type: emptyDir
        medium: Memory

      media:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/tank/media
        globalMounts:
          - path: /media
            readOnly: false
