---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./authelia/ks.yaml
  - ./docmost/ks.yaml
  - ./filebrowser/ks.yaml
  - ./glauth/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/ks.yaml
  - ./nesting/ks.yaml
  - ./nextcloud/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./theme-park/ks.yaml
  - ./vaultwarden/ks.yaml
