instance:
  distribution:
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:v0.61.0
    version: 2.x
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    size: small
    networkPolicy: false
  sync:
    kind: GitRepository
    url: https://github.com/heavybullets8/heavy-ops
    ref: refs/heads/feat/upcloud-talos-trial-20261002
    path: clusters/upcloud-trial/kubernetes
    interval: 1m
