---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb
  namespace: database
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mariadb

  values:
    image:
        repository: bitnamilegacy/mariadb

    auth:
      usePasswordFiles: false
      existingSecret: mariadb-secret
      rootPasswordKey: mariadb-root-password

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    primary:
      extraEnvVars:
        - name: BOOKSTACK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: bookstack-password
      persistence:
        enabled: true
        existingClaim: *app

    initdbScripts:
      create-bookstack.sh: |
        #!/bin/bash
        set -euo pipefail

        bookstack_password_escaped="$(printf '%s' "$${BOOKSTACK_PASSWORD:?missing bookstack password}" | sed "s/'/''/g")"

        mariadb -uroot -p"$${MARIADB_ROOT_PASSWORD:?missing root password}" <<SQL
        CREATE DATABASE IF NOT EXISTS bookstack;
        CREATE USER IF NOT EXISTS 'bookstack'@'%' IDENTIFIED BY '$${bookstack_password_escaped}';
        GRANT ALL PRIVILEGES ON bookstack.* TO 'bookstack'@'%';
        FLUSH PRIVILEGES;
        SQL
