apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cb-ha-storage
  namespace: business-ha-production
  labels:
    substitution.flux.home.arpa/disabled: 'true'
spec:
  path: ./kubernetes/cloud/apps/business-ha-production/cb-ha/storage
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  deletionPolicy: Orphan
  suspend: true
  targetNamespace: business-ha-production
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cb-ha-secrets
  namespace: business-ha-production
  labels:
    substitution.flux.home.arpa/disabled: 'true'
spec:
  path: ./kubernetes/cloud/apps/business-ha-production/cb-ha/secrets
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  deletionPolicy: Orphan
  suspend: true
  dependsOn:
  - name: onepassword-store
    namespace: external-secrets
  targetNamespace: business-ha-production
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cb-ha-runtime
  namespace: business-ha-production
  labels:
    substitution.flux.home.arpa/disabled: 'true'
spec:
  path: ./kubernetes/cloud/apps/business-ha-production/cb-ha/app
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  deletionPolicy: Orphan
  suspend: true
  dependsOn:
  - name: cb-ha-storage
    namespace: business-ha-production
  - name: cb-ha-secrets
    namespace: business-ha-production
  - name: reloader
    namespace: kube-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cb-ha-domains
      optional: false
    - kind: ConfigMap
      name: cb-ha-release
      optional: false
  targetNamespace: business-ha-production
