---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app connelybrothers-web-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    template:
      data:
        DATABASE_URL: "postgres://{{ .CONNELYBROTHERS_POSTGRES_USER }}:{{ .CONNELYBROTHERS_POSTGRES_PASS | urlquery }}@patroni.database.svc.cluster.local:5432/{{ .CONNELYBROTHERS_POSTGRES_DB }}?sslmode=disable"
        HA_OUTBOX_PEER_DATABASE_URL: "postgres://{{ .CONNELYBROTHERS_POSTGRES_OBSERVER_USER }}:{{ .CONNELYBROTHERS_POSTGRES_OBSERVER_PASS | urlquery }}@patroni.database.svc.cluster.local:5433/{{ .CONNELYBROTHERS_POSTGRES_DB }}?sslmode=disable"
        ADMIN_USERNAME: "{{ .CONNELYBROTHERS_ADMIN_USERNAME }}"
        ADMIN_PASSWORD_HASH: "{{ .CONNELYBROTHERS_ADMIN_PASSWORD_HASH }}"
        R2_ACCOUNT_ID: "{{ .CONNELYBROTHERS_R2_ACCOUNT_ID }}"
        R2_ACCESS_KEY_ID: "{{ .CONNELYBROTHERS_R2_ACCESS_KEY_ID }}"
        R2_SECRET_ACCESS_KEY: "{{ .CONNELYBROTHERS_R2_SECRET_ACCESS_KEY }}"
        R2_BUCKET_NAME: "{{ .CONNELYBROTHERS_R2_BUCKET_NAME }}"
        R2_PUBLIC_URL: "{{ .CONNELYBROTHERS_R2_PUBLIC_URL }}"
        GOOGLE_MAPS_PUBLIC_API_KEY: "{{ .CONNELYBROTHERS_GOOGLE_MAPS_PUBLIC_API_KEY }}"
        GOOGLE_MAPS_ADMIN_API_KEY: "{{ .CONNELYBROTHERS_GOOGLE_MAPS_ADMIN_API_KEY }}"
        TURNSTILE_SITE_KEY: "{{ .CONNELYBROTHERS_TURNSTILE_SITE_KEY }}"
        TURNSTILE_SECRET_KEY: "{{ .CONNELYBROTHERS_TURNSTILE_SECRET_KEY }}"
        CLOUDFLARE_CACHE_PURGE_TOKEN: "{{ .CONNELYBROTHERS_CLOUDFLARE_CACHE_PURGE_TOKEN }}"
        CLOUDFLARE_ZONE_IDS: "{{ .CONNELYBROTHERS_CLOUDFLARE_ZONE_IDS }}"
  dataFrom:
    - extract:
        key: connelybrothers
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CONNELYBROTHERS_$1"
