---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patroni-ssh-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patroni-ssh-secret
    template:
      data:
        id_ed25519: "{{ .PATRONI_HOME_SSH_PRIVATE_KEY }}"
        known_hosts: "{{ .PATRONI_HOME_KNOWN_HOSTS }}"
  dataFrom:
    - extract:
        key: patroni
      rewrite:
        - regexp:
            source: "(.*)"
            target: "PATRONI_$1"
