---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patroni-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patroni-secret
    template:
      data:
        PATRONI_SUPERUSER_PASSWORD: "{{ .PATRONI_SUPER_PASS }}"
        PATRONI_REPLICATION_PASSWORD: "{{ .PATRONI_REPLICATION_PASS }}"
        PATRONI_REWIND_PASSWORD: "{{ .PATRONI_REWIND_PASS }}"
        PATRONI_RESTAPI_USERNAME: "{{ .PATRONI_REST_USERNAME }}"
        PATRONI_RESTAPI_PASSWORD: "{{ .PATRONI_REST_PASSWORD }}"
  dataFrom:
    - extract:
        key: patroni
      rewrite:
        - regexp:
            source: "(.*)"
            target: "PATRONI_$1"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patroni-backup-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patroni-backup-secret
    template:
      data:
        pgbackrest.conf: "{{ .PATRONI_PGBACKREST_CONF }}"
  dataFrom:
    - extract:
        key: patroni
      rewrite:
        - regexp:
            source: "(.*)"
            target: "PATRONI_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patroni-ssh-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patroni-ssh-secret
    template:
      data:
        id_ed25519: "{{ .PATRONI_HOME_SSH_PRIVATE_KEY }}"
        known_hosts: "{{ .PATRONI_HOME_KNOWN_HOSTS }}"
  dataFrom:
    - extract:
        key: patroni
      rewrite:
        - regexp:
            source: "(.*)"
            target: "PATRONI_$1"
