---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.k8s.io/networkpolicy_v1.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: patroni
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: business
          podSelector:
            matchLabels:
              app.kubernetes.io/name: connelybrothers-web
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: business
          podSelector:
            matchLabels:
              app.kubernetes.io/name: connelybrothers-origin
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8008
        - protocol: TCP
          port: 9187
        - protocol: TCP
          port: 9188
        - protocol: TCP
          port: 25433
