---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-business
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-business-secret
    template:
      data:
        ORIGIN_CA_API_TOKEN: "{{ .ORIGIN_CA_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare-business
