---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    fullnameOverride: victoria-logs
    retentionPeriod: 14d
    server:
      persistentVolume:
        enabled: true
        storageClassName: openebs-hostpath
        size: 20Gi
      serviceMonitor:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}/?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - name: victoria-logs.${SECRET_DOMAIN}
            path: /
            pathType: Prefix
    dashboards:
      enabled: true
