apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: business-ha-production
components:
- ../../../../../components/cb-ha
resources:
- configmap.yaml
- statefulset.yaml
- service.yaml
