apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: connelybrothers-origin
spec:
  endpoints:
    - dnsName: connely-ha-home.bighornbyte.com
      recordType: CNAME
      targets:
        - home.bighornbyte.com
