apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: business-ha-production
resources:
- namespace.yaml
- ../../../components/common/sops
- cb-ha-domains.secret.sops.yaml
- cb-ha/release.yaml
- cb-ha/ks.yaml
