---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: node-memory-high-utilization
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
