---
apiVersion: "external-secrets.io/v1"
kind: "ExternalSecret"
metadata:
  name: "dealer-agent"
spec:
  secretStoreRef:
    kind: "ClusterSecretStore"
    name: "dealer-agent-onepassword"
  target:
    name: "dealer-agent"
  data:
    - secretKey: "ASSISTANT_BROKER_SECRET"
      remoteRef:
        key: "jm-trailer-development"
        property: "ASSISTANT_BROKER_SECRET"
    - secretKey: "ASSISTANT_RUNTIME_MASTER_SECRET"
      remoteRef:
        key: "jm-trailer-development"
        property: "ASSISTANT_RUNTIME_MASTER_SECRET"
    - secretKey: "OPENAI_API_KEY"
      remoteRef:
        key: "OpenAI-development"
        property: "OPENAI_API_KEY"
