---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-web-client
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-web-client
    template:
      data:
        client-id: "{{ .OAUTH_CLIENT_ID }}"
        client-secret: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: flux-web
