apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ha-home-origin
  namespace: business-ha-production
spec:
  endpoints:
  - dnsName: ${CB_PROD_HOME_FQDN}
    recordType: CNAME
    targets:
    - home.bighornbyte.com
