---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app notifiarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: kopiur
      namespace: kopiur-system

  values:
    controllers:
      notifiarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/notifiarr/notifiarr
              tag: v0.9.7@sha256:2b0a8784d8a43177cbc5a19110e7eb066d9321572c3352eda79c0a89898c7735
            env:
              TZ: ${TIMEZONE}
              DN_UPSTREAMS_0: "[10.96.0.0/16,10.69.0.0/16]"
              TMPDIR: /tmp
              DN_RADARR_0_URL: http://radarr.media.svc.cluster.local
              DN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
              DN_PLEX_URL: http://plex.media.svc.cluster.local:32400
              DN_TAUTULLI_URL: http://tautulli.media.svc.cluster.local
            envFrom:
              - secretRef:
                  name: notifiarr-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 3Gi

    defaultPodOptions:
      hostname: notifiarr-talos
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: 5454

    route:
      app:
        hostnames:
          - "notifiarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        existingClaim: *app

      tmp:
        type: emptyDir
        medium: Memory
