---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-business
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cloudflare-ddns-business-secret
    template:
      data:
        CF_APITOKEN: "{{ .EXTERNAL_DNS_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare-business
