---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scale-tv-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: scale-tv-secret
    template:
      data:
        PGUSER: "{{ .POSTGRES_USER }}"
        PGPASSWORD: "{{ .POSTGRES_PASS }}"
        CLOUDFLARE_ACCOUNT_ID: '{{ index . "CLOUDFLARE_ACCOUNT_ID" | default "" }}'
        CLOUDFLARE_EMAIL_API_TOKEN: '{{ index . "CLOUDFLARE_EMAIL_API_TOKEN" | default "" }}'
        TURNSTILE_SITE_KEY: "{{ .TURNSTILE_SITE_KEY }}"
        TURNSTILE_SECRET_KEY: "{{ .TURNSTILE_SECRET_KEY }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        STRIPE_SECRET_KEY: "{{ .STRIPE_SECRET_KEY }}"
        STRIPE_PUBLISHABLE_KEY: "{{ .STRIPE_PUBLISHABLE_KEY }}"
        STRIPE_WEBHOOK_SECRET: "{{ .STRIPE_WEBHOOK_SECRET }}"
        PLEX_OWNER_TOKEN: "{{ .PLEX_OWNER_TOKEN }}"
  dataFrom:
    - extract:
        key: scale-tv-business-runtime
