apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-store
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  path: ./kubernetes/cloud/apps/external-secrets/onepassword/store
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: onepassword
    namespace: external-secrets
