---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: business
components:
  - ../../../../../components/connelybrothers-origin
patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: ${CB_PROD_CLOUD_FQDN}
