---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: upcloud-business-origin
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/mnt/business-origin
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - trial-talos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &app connelybrothers-origin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: upcloud-business-origin
  resources:
    requests:
      storage: 2Gi
