---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app connelybrothers-web
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: trial-talos
    controllers:
      connelybrothers-web:

        containers:
          app:
            env:
              HA_SITE: cloud
