---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
resources:
  - ./cloudflare-ddns/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./external-service/ks.yaml
  - ./nginx/ks.yaml
